version: 2

models:
  - name: fact_yellow_trip
    description: >
      Core fact table for yellow taxi trips. Includes financial metrics, foreign keys to dimensions,
      and derived time fields for analysis. Uses incremental loading strategy.
    columns:
      - name: trip_id
        description: Unique sequential identifier for each trip.
        tests: [unique, not_null]
        
      - name: trip_date
        description: Trip date (FK to dim_date.date_id).
        tests: 
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_id
              
      - name: pickup_ts
        description: Pickup timestamp.
        tests: [not_null]
        
      - name: dropoff_ts
        description: Dropoff timestamp.
        tests: [not_null]
        
      - name: pickup_hour
        description: Hour extracted from pickup_ts (0-23).
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0 and <= 23"
              
      - name: pickup_weekday_num
        description: Numeric day of week from Snowflake DAYOFWEEK() (0=Sunday, 6=Saturday).
        tests:
          - accepted_values:
              values: [0, 1, 2, 3, 4, 5, 6]
              
      - name: trip_duration_min
        description: Trip duration in minutes (calculated from pickup/dropoff timestamps).
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
              
      - name: vendorid
        description: FK to dim_vendor.
        tests: 
          - not_null
          - relationships:
              to: ref('dim_vendor')
              field: vendorid
              
      - name: passenger_count
        description: Number of passengers.
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
              
      - name: trip_distance
        description: Trip distance in miles.
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
              
      - name: store_and_fwd_flag
        description: Whether trip data was held in vehicle memory (Y/N).
        tests:
          - accepted_values:
              values: ['Y', 'N']
              quote: true
              
      - name: ratecodeid
        description: FK to dim_rate_code.
        tests: 
          - not_null
          - relationships:
              to: ref('dim_rate_code')
              field: ratecodeid
              
      - name: payment_type
        description: FK to dim_payment.
        tests: 
          - not_null
          - relationships:
              to: ref('dim_payment')
              field: payment_type
              
      - name: pulocationid
        description: Pickup location ID (FK to dim_location_zone).
        tests: 
          - not_null
          - relationships:
              to: ref('dim_location_zone')
              field: location_id
              
      - name: dolocationid
        description: Dropoff location ID (FK to dim_location_zone).
        tests: 
          - not_null
          - relationships:
              to: ref('dim_location_zone')
              field: location_id
              
      - name: fare_amount
        description: Base fare amount for the trip.
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
              
      - name: extra
        description: Miscellaneous extras and surcharges.
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
              
      - name: mta_tax
        description: MTA tax automatically triggered based on metered rate.
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
              
      - name: tip_amount
        description: Tip amount (automatically populated for credit card tips).
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
              
      - name: tolls_amount
        description: Total amount of all tolls paid.
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
              
      - name: improvement_surcharge
        description: $0.30 improvement surcharge assessed on hailed trips.
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
              
      - name: congestion_surcharge
        description: Congestion surcharge for trips in congestion zone.
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
              
      - name: airport_fee
        description: Airport fee if applicable.
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
              
      - name: total_amount
        description: Total amount charged to passengers (includes all fees and tip).
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
              
      - name: dbt_loaded_at
        description: Timestamp when record was loaded into the fact table.
        tests: [not_null]